# ---------------------------------------------
# Cloud Build: Build → Push → Deploy to Cloud Run
# ---------------------------------------------

serviceAccount: projects/reputehq-partner-profile/serviceAccounts/github-deployer@reputehq-partner-profile.iam.gserviceaccount.com

logsBucket: gs://reputehq-build-logs

options:
  machineType: E2_HIGHCPU_8

steps:
  # -----------------------------------------------------
  # Step 1 — Build Docker Image
  # -----------------------------------------------------
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - -t
      - europe-west2-docker.pkg.dev/$PROJECT_ID/reputehq-frontend/reputehq-ai:$COMMIT_SHA
      - .

  # -----------------------------------------------------
  # Step 2 — Push Image to Artifact Registry
  # -----------------------------------------------------
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - europe-west2-docker.pkg.dev/$PROJECT_ID/reputehq-frontend/reputehq-ai:$COMMIT_SHA

  # -----------------------------------------------------
  # Step 3 — Deploy to Cloud Run
  # -----------------------------------------------------
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - reputehq-frontend
      - --image=europe-west2-docker.pkg.dev/$PROJECT_ID/reputehq-frontend/reputehq-ai:$COMMIT_SHA
      - --region=europe-west2
      - --platform=managed
      - --allow-unauthenticated

images:
  - europe-west2-docker.pkg.dev/$PROJECT_ID/reputehq-frontend/reputehq-ai:$COMMIT_SHA
