# ---------------------------------------------
# Cloud Build: Generate config.js → Build → Push → Deploy to Cloud Run
# ---------------------------------------------

serviceAccount: projects/reputehq-partner-profile/serviceAccounts/github-deployer@reputehq-partner-profile.iam.gserviceaccount.com

logsBucket: gs://reputehq-build-logs

options:
  machineType: E2_HIGHCPU_8

# Custom substitutions for frontend-safe keys
substitutions:
  _SUPABASE_URL: "https://backend-server-1-dev.supabase.co"  # replace with your actual Supabase project URL
  _SUPABASE_ANON_KEY: "YOUR_ANON_KEY"                          # safe to expose to frontend

steps:
  # Step 0 — Generate config.js from template using custom substitutions
  - name: gcr.io/cloud-builders/gcloud
    id: GenerateConfig
    entrypoint: bash
    env:
      - _SUPABASE_URL
      - _SUPABASE_ANON_KEY
    args:
      - -c
      - |
        echo "Generating config.js from template..."
        mkdir -p public
        sed -e "s|__SUPABASE_URL__|${_SUPABASE_URL}|g" \
            -e "s|__SUPABASE_ANON_KEY__|${_SUPABASE_ANON_KEY}|g" \
            src/config.template.js > public/config.js
        echo "config.js generated at public/config.js"

  # Step 1 — Build Docker Image
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - -t
      - europe-west2-docker.pkg.dev/$PROJECT_ID/reputehq-frontend/reputehq-ai:$COMMIT_SHA
      - .

  # Step 2 — Push Image to Artifact Registry
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - europe-west2-docker.pkg.dev/$PROJECT_ID/reputehq-frontend/reputehq-ai:$COMMIT_SHA

  # Step 3 — Deploy to Cloud Run
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    id: Deploy
    entrypoint: gcloud
    args:
      - run
      - deploy
      - reputehq-frontend
      - --image=europe-west2-docker.pkg.dev/$PROJECT_ID/reputehq-frontend/reputehq-ai:$COMMIT_SHA
      - --region=europe-west2
      - --platform=managed
      - --allow-unauthenticated

images:
  - europe-west2-docker.pkg.dev/$PROJECT_ID/reputehq-frontend/reputehq-ai:$COMMIT_SHA
