# -------------------------------------------------------
# ReputeHQ Production Cloud Build Configuration
# -------------------------------------------------------

# Custom service account
serviceAccount: projects/reputehq-partner-profile/serviceAccounts/github-deployer@reputehq-partner-profile.iam.gserviceaccount.com

# Logs bucket
logsBucket: gs://reputehq-build-logs

# Optional machine type
options:
  machineType: E2_HIGHCPU_8

# -----------------------------
# Build & Push Steps
# -----------------------------
steps:
  # -----------------------------------------------------
  # Step 1 — Build Docker Image
  # -----------------------------------------------------
  - name: gcr.io/cloud-builders/docker
    id: Build
    args:
      - build
      - -t
      - europe-west2-docker.pkg.dev/$PROJECT_ID/reputehq-frontend/reputehq-ai:$COMMIT_SHA
      - .

  # -----------------------------------------------------
  # Step 2 — Push Image to Artifact Registry
  # -----------------------------------------------------
  - name: gcr.io/cloud-builders/docker
    id: Push
    args:
      - push
      - europe-west2-docker.pkg.dev/$PROJECT_ID/reputehq-frontend/reputehq-ai:$COMMIT_SHA

# -----------------------------
# Register the image for Cloud Build
# -----------------------------
images:
  - europe-west2-docker.pkg.dev/$PROJECT_ID/reputehq-frontend/reputehq-ai:$COMMIT_SHA
