# Use lightweight Python image
FROM python:3.11-alpine

# Set working directory
WORKDIR /app

# Copy all web frontend files into the public folder
COPY . ./public/

# Set Cloud Run port
ENV PORT 8080

# Expose port
EXPOSE 8080

# Serve the public directory via Python's built-in HTTP server
# config.js was already generated by the Cloud Build step before this runs
CMD ["sh", "-c", "cd public && python -m http.server $PORT"]
